# Generated by Django 6.0.7 on 2026-07-16 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MSF - SARL', max_length=180, verbose_name='Nom de la société')),
                ('legal_name', models.CharField(blank=True, default='MSF - SARL', max_length=220, verbose_name='Raison sociale')),
                ('activity', models.CharField(blank=True, default='Électricité, sanitaire, plomberie, peinture, cuisine et divers', max_length=255, verbose_name='Activité')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('address', models.TextField(blank=True, default="N'Golonina, non loin de la mosquée de NIMAGA", verbose_name='Adresse')),
                ('phone', models.CharField(blank=True, default='+223 76 84 79 79 / 70 70 65 77 / 75 75 19 58 / 79 30 43 81', max_length=120, verbose_name='Téléphone principal')),
                ('phone_secondary', models.CharField(blank=True, max_length=120, verbose_name='Téléphone secondaire')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail')),
                ('website', models.CharField(blank=True, max_length=180, verbose_name='Site web')),
                ('rccm', models.CharField(blank=True, max_length=120, verbose_name='RCCM')),
                ('nif', models.CharField(blank=True, max_length=120, verbose_name='NIF')),
                ('bank_details', models.TextField(blank=True, verbose_name='Coordonnées bancaires')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Logo de la société')),
                ('invoice_header_mode', models.CharField(choices=[('generated', 'Entête générée automatiquement'), ('image', 'Image d’entête personnalisée')], default='image', max_length=20, verbose_name='Type d’entête des factures')),
                ('invoice_header', models.ImageField(blank=True, null=True, upload_to='company/invoice_headers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'webp'])], verbose_name='Image d’entête personnalisée')),
                ('invoice_header_height_mm', models.PositiveSmallIntegerField(default=44, help_text='Valeur recommandée : entre 35 et 50 mm.', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(80)], verbose_name='Hauteur de l’entête')),
                ('show_logo_on_generated_header', models.BooleanField(default=True, verbose_name='Afficher le logo sur l’entête automatique')),
                ('invoice_footer_text', models.TextField(blank=True, default='Merci pour votre confiance.', verbose_name='Texte de pied de facture')),
                ('invoice_terms', models.TextField(blank=True, default='Les marchandises vendues ne sont ni reprises ni échangées sauf accord préalable.', verbose_name='Conditions ou observations')),
                ('currency_label', models.CharField(default='F CFA', max_length=30, verbose_name='Devise affichée')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètre de la société',
                'verbose_name_plural': 'Paramètres de la société',
            },
        ),
    ]
