# Generated by Django 6.0.7 on 2026-07-12 08:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='Titre')),
                ('category', models.CharField(choices=[('rent', 'Loyer'), ('transport', 'Transport'), ('salary', 'Salaire'), ('food', 'Nourriture'), ('electricity', 'Électricité'), ('internet', 'Internet'), ('maintenance', 'Maintenance'), ('other', 'Autre')], default='other', max_length=30, verbose_name='Catégorie')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant')),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date dépense')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date'],
                'indexes': [models.Index(fields=['expense_date'], name='expenses_ex_expense_cf8a73_idx'), models.Index(fields=['category'], name='expenses_ex_categor_fcaba7_idx')],
            },
        ),
    ]
