# Generated by Django 6.0.7 on 2026-07-15 06:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du fournisseur')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Adresse e-mail')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Dette fournisseur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Fournisseur actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Fournisseur',
                'verbose_name_plural': 'Fournisseurs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='purchases_s_name_df4648_idx'), models.Index(fields=['phone'], name='purchases_s_phone_9eb47a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name="Numéro d'achat")),
                ('supplier_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence fournisseur')),
                ('purchase_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'achat")),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remise globale')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total net')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant payé')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Reste à payer')),
                ('payment_status', models.CharField(choices=[('paid', 'Payé'), ('partial', 'Partiel'), ('credit', 'Crédit'), ('cancelled', 'Annulé')], default='credit', max_length=20, verbose_name='Statut du paiement')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèce'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire'), ('credit', 'Crédit'), ('other', 'Autre')], default='cash', max_length=30, verbose_name='Mode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Achat annulé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='purchases.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Achat',
                'verbose_name_plural': 'Achats',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name="Prix d'achat unitaire")),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remise sur la ligne')),
                ('total_line', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant de la ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='catalog.product', verbose_name='Produit')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchase', verbose_name='Achat')),
            ],
            options={
                'verbose_name': "Ligne d'achat",
                'verbose_name_plural': "Lignes d'achat",
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('purchase', 'product'), name='unique_product_per_purchase')],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Montant payé')),
                ('payment_method', models.CharField(choices=[('cash', 'Espèce'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire'), ('other', 'Autre')], default='cash', max_length=30, verbose_name='Mode de paiement')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_payments', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchases.purchase', verbose_name='Achat')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.supplier', verbose_name='Fournisseur')),
            ],
            options={
                'verbose_name': 'Paiement fournisseur',
                'verbose_name_plural': 'Paiements fournisseurs',
                'ordering': ['-payment_date'],
                'indexes': [models.Index(fields=['payment_date'], name='purchases_p_payment_0091f4_idx'), models.Index(fields=['payment_method'], name='purchases_p_payment_561afe_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_number'], name='purchases_p_purchas_12ae8f_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['purchase_date'], name='purchases_p_purchas_f942b0_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['payment_status'], name='purchases_p_payment_5a0679_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['is_cancelled'], name='purchases_p_is_canc_76a7ab_idx'),
        ),
    ]
