# Generated by Django 6.0.7 on 2026-07-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': 'Mouvement de stock', 'verbose_name_plural': 'Mouvements de stock'},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_reference',
            field=models.CharField(blank=True, db_index=True, help_text='Référence commune aux produits enregistrés dans la même entrée ou la même sortie.', max_length=80, verbose_name='Référence du bon'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['batch_reference', 'movement_type'], name='inventory_s_batch_r_1c4fa1_idx'),
        ),
    ]
