# Generated by Django 6.0.7 on 2026-07-17 22:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import documents.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proforma_number', models.CharField(blank=True, max_length=40, unique=True, verbose_name='Numéro de proforma')),
                ('proforma_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de la proforma')),
                ('valid_until', models.DateField(default=documents.models.default_valid_until, verbose_name='Valable jusqu’au')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Sous-total')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remise globale')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total net')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('accepted', 'Acceptée'), ('rejected', 'Refusée'), ('converted', 'Convertie en vente'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('terms', models.TextField(blank=True, default='Cette proforma est valable jusqu’à la date indiquée. Les prix et les disponibilités peuvent évoluer après expiration.', verbose_name='Conditions commerciales')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proformas', to='customers.client', verbose_name='Client')),
                ('converted_sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proforma', to='sales.sale', verbose_name='Vente créée')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proformas', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Proforma',
                'verbose_name_plural': 'Proformas',
                'ordering': ['-proforma_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProformaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Prix unitaire proposé')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Remise de la ligne')),
                ('total_line', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Montant de la ligne')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_items', to='catalog.product', verbose_name='Produit')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.proforma', verbose_name='Proforma')),
            ],
            options={
                'verbose_name': 'Ligne de proforma',
                'verbose_name_plural': 'Lignes de proforma',
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['proforma_number'], name='documents_p_proform_ea7ae8_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['proforma_date'], name='documents_p_proform_1c670c_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['valid_until'], name='documents_p_valid_u_e61433_idx'),
        ),
        migrations.AddIndex(
            model_name='proforma',
            index=models.Index(fields=['status'], name='documents_p_status_939046_idx'),
        ),
        migrations.AddConstraint(
            model_name='proformaitem',
            constraint=models.UniqueConstraint(fields=('proforma', 'product'), name='unique_product_per_proforma'),
        ),
        migrations.AddConstraint(
            model_name='proformaitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', Decimal('0.00'))), name='proforma_item_quantity_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='proformaitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', Decimal('0.00'))), name='proforma_item_unit_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='proformaitem',
            constraint=models.CheckConstraint(condition=models.Q(('discount__gte', Decimal('0.00'))), name='proforma_item_discount_gte_zero'),
        ),
    ]
