# Generated by Django 6.0.7 on 2026-07-12 08:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='Nom complet')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Dette totale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['full_name'],
                'indexes': [models.Index(fields=['full_name'], name='customers_c_full_na_5e6294_idx'), models.Index(fields=['phone'], name='customers_c_phone_be3650_idx')],
            },
        ),
    ]
