# Generated by Django 6.0.7 on 2026-07-12 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashbox', '0002_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='sales.sale', verbose_name='Vente'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['movement_type'], name='cashbox_cas_movemen_0d58d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashmovement',
            index=models.Index(fields=['movement_date'], name='cashbox_cas_movemen_e70f93_idx'),
        ),
    ]
